# Generated by Django 4.0.4 on 2022-05-29 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkStation',
        ),
    ]
